### ISSUE TITLE
安装教程不是很明白

### ISSUE THREAD

**Issue by zerolanlan** [19920625lsg/spring-boot-online-exam#48]
请问在spring-boot-online-exam/backend/exam/src/main/resources/application.yml中是没有password的选项的，只有后面application-dev和application-prod有而且密码不一样，希望能重新更新一下安装配置教程，新手真的好难看懂，谢谢，辛苦了

**Comment by izumiiAoba** [comment]
### application.yml
```yml
spring:
  profiles:
    active: dev # 开发时配dev, 生产环境配prod，如果容器化直接运行make_docker.sh即可这里配啥无所谓
```
这边的`dev`就是来指明是使用`application-dev.yml`中的配置，所以改的数据库密码是这边的。
